module.exports = broNames = [
	'Abroham Lincoln',
	'Albert PuBrols',
	'Angeline Brolie',
	'Axel Brose',
	'Bro Jackson',
	'Bro Montana',
	'Bro Peche',
	'BRO.J. Simpson',
	'BrobaFett',
	'Brobi Wan Kinobi',
	'Brobocop',
	'Brocahontas',
	'Brohammad Ali',
	'Brohan Solo',
	'Brohemian',
	'Broprah Winfrey',
	'Brorannasaurs Rex',
	'Brosa Parks',
	'Broseph',
	'Broseph Stalin',
	'Brosideon',
	"Brosie O'Donnell",
	'Broski',
	'Brotato chip',
	'Brotein Shake',
	'Brovolone Cheese',
	'Brozo the Clown',
	'C-3PBro',
	'Dikembe Mutumbro',
	'GI Bro',
	"Guns n' Broses",
	'Han Brolo',
	'Hulk Brogan',
	'Joe Brogan',
	'Kimbro slice',
	'Kurt Brobain',
	'Lindsey Brohan',
	'Marilyn Monbro',
	'REBro Speedwagon',
	'Ringbro Starr',
	'Robert Denirbro',
	'RobroCop',
	'Rocky Balbroa',
	'Russel Bro',
	'Sandy Broufax',
	'Scarlette Brohanson',
	'Seth Brogan',
	"Shaquille Bro'neil",
	'Sheryl Bro',
	'Sonny Brono',
	'Teddy Broosevelt',
	'The Big Brobowski',
	'Tim Tebrow',
	'Vincent Van Brogh',
	'The Brope, leader of the Broman Catholic Church',
	'KC and BroBro',
	'NaBroleon Dynamite',
	'Evander Brolyfield',
	'Tony Bromo',
];
